### ISSUE TITLE
Pickle Unpickling Error

### ISSUE THREAD

**Issue by sirhikesalot** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#22]
Thank you for your great work! I am getting pickle unloading error with both pre-trained weights checkpoint_epoch_70.pth and mobilenet_sgd_68.848.pth.tar. 

Traceback (most recent call last):
  File "val.py", line 138, in <module>
    checkpoint = torch.load(args.checkpoint_path)
  File "/home/ubuntu/anaconda3/envs/gccpm/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/anaconda3/envs/gccpm/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

Any help would be much appreciated.

**Comment by sirhikesalot** [comment]
I've fixed my issue. It was my wget command to the google drive download. Required different syntax given it is a classified by google as a large file. Closing this issue.
