### ISSUE TITLE
problem when train from checkpoints

### ISSUE THREAD

**Issue by JiangDing1995** [Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch#7]
Hi,thank you for your work! i have 2 questions here:
1.When i want to continue training from the "checkpoint_epoch_39.pth"(i trained 40 epochs),here is the error:
robeon@robeon-MS:~/pytorch-GCCPM$ python train.py --dataset-folder /home/robeon/pytorch-GCCPM/LIP --checkpoint-path /home/robeon/pytorch-GCCPM/default_checkpoints/checkpoint_epoch_39.pth.tar

Traceback (most recent call last):
  File "train.py", line 171, in <module>
    checkpoints_folder, args.log_after, args.checkpoint_after)
  File "train.py", line 62, in train
    checkpoint = torch.load(checkpoint_path)
  File "/home/robeon/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/robeon/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/home/robeon/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/robeon/anaconda3/lib/python3.6/tarfile.py", line 2041, in extract
    tarinfo = self.getmember(member)
  File "/home/robeon/anaconda3/lib/python3.6/tarfile.py", line 1752, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

i dont't know how to solve this
2.How to drop the learning-rate?Does the code drops itself or i need to modify the base_lr by myself and continue training?

thanks again!

**Comment by JiangDing1995** [comment]
oh,sorry for my mistake, i just set the epoch in range 10 when i want to continue training:
"for epochId in range(current_epoch, 10):",here it should set such as 50. now i have solved the problem 1.Also, may be i am right with problem 2.
thanks

**Comment by Daniil-Osokin** [comment]
It drops learning rate automatically if validation accuracy stopped increasing for some epoches by using [ReduceLROnPlateau](https://github.com/Daniil-Osokin/gccpm-look-into-person-cvpr19.pytorch/blob/master/train.py#L60) scheduler.

**Comment by JiangDing1995** [comment]
thank you
